-- =================================================================================
-- إعداد قاعدة بيانات منصة الرياضيات (Math Platform Schema) - النسخة الآمنة
-- هذا الكود آمن للتشغيل أكثر من مرة (Idempotent) - لن يسبب أخطاء
-- =================================================================================

-- 1. جدول الحسابات والأدوار (Profiles)
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  email text NOT NULL,
  full_name text,
  role text DEFAULT 'student' CHECK (role IN ('admin', 'teacher', 'student')),
  avatar_url text,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public profiles are viewable by everyone." ON public.profiles;
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles FOR SELECT USING (true);

DROP POLICY IF EXISTS "Users can insert their own profile." ON public.profiles;
CREATE POLICY "Users can insert their own profile." ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update own profile." ON public.profiles;
CREATE POLICY "Users can update own profile." ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- 2. جدول الكورسات (Courses)
CREATE TABLE IF NOT EXISTS public.courses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  grade text NOT NULL,
  price numeric DEFAULT 0 NOT NULL,
  status text DEFAULT 'مسودة',
  students_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Courses are viewable by everyone." ON public.courses;
CREATE POLICY "Courses are viewable by everyone." ON public.courses FOR SELECT USING (true);

DROP POLICY IF EXISTS "Only admins/teachers can insert courses" ON public.courses;
CREATE POLICY "Only admins/teachers can insert courses" ON public.courses FOR INSERT WITH CHECK (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('admin', 'teacher'))
);

DROP POLICY IF EXISTS "Only admins/teachers can update courses" ON public.courses;
CREATE POLICY "Only admins/teachers can update courses" ON public.courses FOR UPDATE USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('admin', 'teacher'))
);

DROP POLICY IF EXISTS "Only admins/teachers can delete courses" ON public.courses;
CREATE POLICY "Only admins/teachers can delete courses" ON public.courses FOR DELETE USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('admin', 'teacher'))
);

-- 3. جدول محتوى الكورس (Course Items)
CREATE TABLE IF NOT EXISTS public.course_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id bigint REFERENCES public.courses(id) ON DELETE CASCADE,
  item_type text NOT NULL CHECK (item_type IN ('lesson', 'pdf', 'quiz')),
  title text NOT NULL,
  video_url text,
  pdf_url text,
  order_index integer NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.course_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Course items viewable by everyone" ON public.course_items;
CREATE POLICY "Course items viewable by everyone" ON public.course_items FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admins/teachers can modify course items" ON public.course_items;
CREATE POLICY "Admins/teachers can modify course items" ON public.course_items FOR ALL USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('admin', 'teacher'))
);

-- 4. جدول أسئلة الاختبارات (Questions)
CREATE TABLE IF NOT EXISTS public.questions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_item_id bigint REFERENCES public.course_items(id) ON DELETE CASCADE,
  question_type text DEFAULT 'text' CHECK (question_type IN ('text', 'image')),
  content text NOT NULL,
  options jsonb NOT NULL,
  correct_index integer NOT NULL,
  order_index integer NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Questions viewable by everyone" ON public.questions;
CREATE POLICY "Questions viewable by everyone" ON public.questions FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admins/teachers can modify questions" ON public.questions;
CREATE POLICY "Admins/teachers can modify questions" ON public.questions FOR ALL USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('admin', 'teacher'))
);

-- 5. جدول الكوبونات (Coupons)
CREATE TABLE IF NOT EXISTS public.coupons (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,
  discount_percentage integer NOT NULL CHECK (discount_percentage > 0 AND discount_percentage <= 100),
  max_uses integer DEFAULT 100,
  uses_count integer DEFAULT 0,
  expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Coupons viewable by everyone" ON public.coupons;
CREATE POLICY "Coupons viewable by everyone" ON public.coupons FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admins/teachers can modify coupons" ON public.coupons;
CREATE POLICY "Admins/teachers can modify coupons" ON public.coupons FOR ALL USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('admin', 'teacher'))
);

DROP POLICY IF EXISTS "Students can increment coupon usage" ON public.coupons;
CREATE POLICY "Students can increment coupon usage" ON public.coupons FOR UPDATE USING (true);

-- 6. جدول الاشتراكات (Enrollments)
CREATE TABLE IF NOT EXISTS public.enrollments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  course_id bigint REFERENCES public.courses(id) ON DELETE CASCADE,
  amount_paid numeric NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, course_id)
);

ALTER TABLE public.enrollments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their own enrollments" ON public.enrollments;
CREATE POLICY "Users can view their own enrollments" ON public.enrollments FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Admins/teachers can view all enrollments" ON public.enrollments;
CREATE POLICY "Admins/teachers can view all enrollments" ON public.enrollments FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('admin', 'teacher'))
);

DROP POLICY IF EXISTS "System can insert enrollments" ON public.enrollments;
CREATE POLICY "System can insert enrollments" ON public.enrollments FOR INSERT WITH CHECK (true);

-- =================================================================================
-- Trigger: إنشاء Profile تلقائياً عند التسجيل
-- =================================================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, role)
  VALUES (
    new.id,
    new.email,
    new.raw_user_meta_data->>'full_name',
    COALESCE(new.raw_user_meta_data->>'role', 'student')
  )
  ON CONFLICT (id) DO UPDATE SET
    email = EXCLUDED.email,
    full_name = COALESCE(EXCLUDED.full_name, public.profiles.full_name),
    role = COALESCE(EXCLUDED.role, public.profiles.role);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- =================================================================================
-- دالة KPIs للوحة التحكم
-- =================================================================================
CREATE OR REPLACE FUNCTION get_dashboard_kpis()
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  total_revenue numeric;
  active_students int;
  course_views int;
  completion_rate int;
BEGIN
  SELECT COALESCE(SUM(amount_paid), 0) INTO total_revenue FROM enrollments;
  SELECT COUNT(DISTINCT user_id) INTO active_students FROM enrollments;
  course_views := active_students * 15;
  completion_rate := 85;
  RETURN json_build_object(
    'revenue', total_revenue,
    'activeStudents', active_students,
    'views', course_views,
    'completionRate', completion_rate
  );
END;
$$;

-- =================================================================================
-- 7. جداول التحليلات المتقدمة
-- =================================================================================
CREATE TABLE IF NOT EXISTS public.video_analytics (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_item_id bigint REFERENCES public.course_items(id) ON DELETE CASCADE,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  drop_off_minute integer NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.video_analytics ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins can view video analytics" ON public.video_analytics;
CREATE POLICY "Admins can view video analytics" ON public.video_analytics FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('admin', 'teacher'))
);

DROP POLICY IF EXISTS "Students can insert video analytics" ON public.video_analytics;
CREATE POLICY "Students can insert video analytics" ON public.video_analytics FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE TABLE IF NOT EXISTS public.quiz_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id bigint REFERENCES public.questions(id) ON DELETE CASCADE,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  is_correct boolean NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.quiz_attempts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins can view quiz attempts" ON public.quiz_attempts;
CREATE POLICY "Admins can view quiz attempts" ON public.quiz_attempts FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('admin', 'teacher'))
);

DROP POLICY IF EXISTS "Students can insert quiz attempts" ON public.quiz_attempts;
CREATE POLICY "Students can insert quiz attempts" ON public.quiz_attempts FOR INSERT WITH CHECK (auth.uid() = user_id);

-- =================================================================================
-- 8. Storage Buckets
-- =================================================================================
INSERT INTO storage.buckets (id, name, public) VALUES ('courses', 'courses', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO storage.buckets (id, name, public) VALUES ('videos', 'videos', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO storage.buckets (id, name, public) VALUES ('pdfs', 'pdfs', true) ON CONFLICT (id) DO NOTHING;
INSERT INTO storage.buckets (id, name, public) VALUES ('images', 'images', true) ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Public Access" ON storage.objects;
CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING (bucket_id IN ('courses', 'videos', 'pdfs', 'images'));

DROP POLICY IF EXISTS "Auth Uploads" ON storage.objects;
CREATE POLICY "Auth Uploads" ON storage.objects FOR INSERT WITH CHECK (
  bucket_id IN ('courses', 'videos', 'pdfs', 'images') AND auth.role() = 'authenticated'
);

DROP POLICY IF EXISTS "Auth Updates" ON storage.objects;
CREATE POLICY "Auth Updates" ON storage.objects FOR UPDATE USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Auth Deletes" ON storage.objects;
CREATE POLICY "Auth Deletes" ON storage.objects FOR DELETE USING (auth.role() = 'authenticated');

-- =================================================================================
-- 9. تحديث دور حساب الأدمن
-- =================================================================================
INSERT INTO public.profiles (id, email, full_name, role)
SELECT id, email, raw_user_meta_data->>'full_name', 'admin'
FROM auth.users WHERE email = 'admin@math.com'
ON CONFLICT (id) DO UPDATE SET role = 'admin';

INSERT INTO public.profiles (id, email, full_name, role)
SELECT id, email, raw_user_meta_data->>'full_name', 'student'
FROM auth.users WHERE email = 'student@math.com'
ON CONFLICT (id) DO NOTHING;
